### ISSUE TITLE
Error executing "CopyObject"

### ISSUE THREAD

**Issue by shubaivan** [thephpleague/flysystem-aws-s3-v3#215] opened 2020-09-09 15:01 UTC
Some problem when try to execute `rename` function. 

```
            "name": "league/flysystem-aws-s3-v3",
            "version": "dev-master",
```

I attemted chnage ACL to public but still had this error
return true when I called `has` function for original file, what problem is here, maybe need reduce verstion ?

```
Error executing "CopyObject" on "https://minimoj-consumer.ams3.digitaloceanspaces.com/minimoj-consumer/minimoj/download_files/adrecord/baby_bjorn/20200909115234_hello_anmol.csv"; AWS HTTP error: Client error: `PUT https://minimoj-consumer.ams3.digitaloceanspaces.com/minimoj-consumer/minimoj/download_files/adrecord/baby_bjorn/20200909115234_hello_anmol.csv` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><BucketName>minimoj-consumer</BucketName><RequestId>t (truncated...)
 NoSuchKey (client):  - <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><BucketName>minimoj-consumer</BucketName><RequestId>tx000000000000083419401-005f58c420-aaf305-ams3b</RequestId><HostId>aaf305-ams3b-ams3-zg02</HostId></Error>
```

**Comment by frankdejonge** [comment] 2020-09-09 15:02
@shubaivan can you supply the key that you're trying to rename?

**Comment by shubaivan** [comment] 2020-09-09 15:09
@frankdejonge perhaps path.. old nad new path

```
    /**
     * Rename a file.
     *
     * @param string $path    Path to the existing file.
     * @param string $newpath The new path of the file.
     *
     * @throws FileExistsException   Thrown if $newpath exists.
     * @throws FileNotFoundException Thrown if $path does not exist.
     *
     * @return bool True on success, false on failure.
     */
    public function rename($path, $newpath);
```

```
'download_files/adrecord/baby_bjorn/20200909115234.csv', 'download_files/adrecord/baby_bjorn/20200909115234_hello_anmol.csv'
```

I faced with this problem when try to used `flysystem-concatenate` plugin, but after debug I undertsand problem with `CopyObject`

**Comment by frankdejonge** [comment] 2020-09-09 15:10
What is the flysystem-concatenate plugin?

**Comment by shubaivan** [comment] 2020-09-09 15:15
[https://github.com/kevengodet/flysystem-concatenate](concatenate)

But problem not with concatenate, becuase I tested directly, just called rename function and faced with that problem

**Comment by shubaivan** [comment] 2020-09-09 15:17
problem is in 

`\League\Flysystem\AwsS3v3\AwsS3Adapter::copy`

ctahed exception

**Comment by frankdejonge** [comment] 2020-09-09 15:19
I think the problem is then at Digital Ocean's end, because it works for normal AWS S3 (just tested 1.x master).

**Comment by frankdejonge** [comment] 2020-09-09 15:20
I used this:

```php
$adapter = new AwsS3Adapter($client, 'bucket-name', 'path-prefix');
$filesystem = new Filesystem($adapter);

var_dump($filesystem->put('something.txt', 'contents'));

var_dump($filesystem->rename('something.txt', 'new-name.txt'));
var_dump($filesystem->read('new-name.txt'));
var_dump($filesystem->delete('new-name.txt'));
```

**Comment by shubaivan** [comment] 2020-09-09 15:44
hm, should I report in DO aobut this ?

**Comment by frankdejonge** [comment] 2020-09-09 15:45
Probably, I've seen more S3 issues come from them that worked on S3. Since their S3 implementation may not be 100% identical, issues like this can come up. It could also be a regression.

**Comment by shubaivan** [comment] 2020-09-09 15:47
you mean if compare amazon s3 and do storage ?

**Comment by frankdejonge** [comment] 2020-09-09 15:48
Yes, they are implemented separately.

**Comment by shubaivan** [comment] 2020-09-09 15:52
but how to work with DO or only one way will switch to aws s3 ?

**Comment by shubaivan** [comment] 2020-09-09 16:16
@frankdejonge or another question what way exist for downloading a big file and use stream ?

**Comment by frankdejonge** [comment] 2020-09-09 16:20
> but how to work with DO or only one way will switch to aws s3 ?

I cannot answer this for you. A safe bet would be to go with AWS S3 since it's more mature than DO S3.

> @frankdejonge or another question what way exist for downloading a big file and use stream ?

Use `readStream`, it's good for memory usage and safe with downloading big files.

**Comment by shubaivan** [comment] 2020-09-09 16:32
@frankdejonge you means `\League\Flysystem\Filesystem::writeStream` ? But if file weight 1gb, I guess it could be problem.
now I use this approach

```
use GuzzleHttp\Client;

$client = new Client();
            $response = $client->request(
                'GET',
                $url,
                [
                    'stream' => true,
                    'version' => '1.0'
                ]
            )->getBody();

        $phpStream = $response->detach();
        unset($client);
        unset($response);

        while (!feof($phpStream)) {
            $read = fread($phpStream, 2048);

            file_put_contents(
                $fileRelativePath,
                $read,
                FILE_APPEND
            );
        }

```

cut 2mb from stream end set in locally, but no wI need save it in some storage, I have digital ocean cred and try to find out how to correct save files wihout thowing limit memory

Do you recomend this way ?


```
        ........
        $phpStream = $response->detach();
        unset($client);
        unset($response);
        $this->do->getStorage()
            ->writeStream($doPath, $phpStream);
```

**Comment by frankdejonge** [comment] 2020-09-09 16:35
I thought you meant downloading it from S3, but if you want to upload to S3, you should indeed use writeStream. I'll close this issue now since the original problem is not fixable in Flysystem.

**Closed by frankdejonge** 2020-09-09 16:35 UTC

**Comment by shubaivan** [comment] 2020-09-09 17:04
@frankdejonge could you look please [stream issue](https://github.com/thephpleague/csv/issues/397) ?

**Comment by frankdejonge** [comment] 2020-09-09 21:08
@shubaivan I think you need to write to disk first and then upload it.
